services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nimbus
      POSTGRES_PASSWORD: nimbus
      POSTGRES_DB: nimbus
    ports:
      - "5432:5432"
    volumes:
      - nimbus_pg:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - nimbus_redis:/data

volumes:
  nimbus_pg:
  nimbus_redis:
